// <auto-generated />
namespace AgendEsport_PI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Cruds : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cruds));
        
        string IMigrationMetadata.Id
        {
            get { return "202212190018182_Cruds"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
