// <auto-generated />
namespace AgendEsport_PI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class jo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jo));
        
        string IMigrationMetadata.Id
        {
            get { return "202301250127099_jo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
